{
  service: 'uny-lost-backend',
  level: 'error',
  message: '❌ Email service initialization failed: nodemailer.createTransporter is not a function',
  stack: 'TypeError: nodemailer.createTransporter is not a function\n' +
    '    at EmailService.initializeTransporter (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:81:37)\n' +
    '    at new EmailService (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:10:10)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:486:34)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1208:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1024:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1233:19)\n' +
    '    at require (node:internal/modules/helpers:179:18)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:12:31)',
  timestamp: '2025-06-16 05:15:03'
}
{
  service: 'uny-lost-backend',
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  original: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
  parameters: {},
  level: 'error',
  message: "❌ Database connection failed: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
  stack: 'Error\n' +
    '    at Query.run (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.createTable (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:98:12)\n' +
    '    at async LostItem.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\model.js:942:7)\n' +
    '    at async Sequelize.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async setupDatabase (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\config\\database.js:82:7)\n' +
    '    at async startServer (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:119:5)',
  timestamp: '2025-06-16 05:15:07'
}
{
  service: 'uny-lost-backend',
  level: 'error',
  message: '❌ Email service initialization failed: nodemailer.createTransporter is not a function',
  stack: 'TypeError: nodemailer.createTransporter is not a function\n' +
    '    at EmailService.initializeTransporter (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:81:37)\n' +
    '    at new EmailService (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:10:10)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:486:34)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1208:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1024:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1233:19)\n' +
    '    at require (node:internal/modules/helpers:179:18)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:12:31)',
  timestamp: '2025-06-16 05:15:26'
}
{
  service: 'uny-lost-backend',
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  original: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
  parameters: {},
  level: 'error',
  message: "❌ Database connection failed: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
  stack: 'Error\n' +
    '    at Query.run (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.createTable (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:98:12)\n' +
    '    at async LostItem.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\model.js:942:7)\n' +
    '    at async Sequelize.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async setupDatabase (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\config\\database.js:82:7)\n' +
    '    at async startServer (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:119:5)',
  timestamp: '2025-06-16 05:15:28'
}
{
  service: 'uny-lost-backend',
  level: 'error',
  message: '❌ Email service initialization failed: nodemailer.createTransporter is not a function',
  stack: 'TypeError: nodemailer.createTransporter is not a function\n' +
    '    at EmailService.initializeTransporter (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:81:37)\n' +
    '    at new EmailService (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:10:10)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:486:34)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1208:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1024:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1233:19)\n' +
    '    at require (node:internal/modules/helpers:179:18)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:12:31)',
  timestamp: '2025-06-16 05:15:44'
}
{
  service: 'uny-lost-backend',
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  original: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
  parameters: {},
  level: 'error',
  message: "❌ Database connection failed: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
  stack: 'Error\n' +
    '    at Query.run (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.createTable (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:98:12)\n' +
    '    at async LostItem.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\model.js:942:7)\n' +
    '    at async Sequelize.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async setupDatabase (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\config\\database.js:82:7)\n' +
    '    at async startServer (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:119:5)',
  timestamp: '2025-06-16 05:15:47'
}
{
  service: 'uny-lost-backend',
  level: 'error',
  message: '❌ Email service initialization failed: nodemailer.createTransporter is not a function',
  stack: 'TypeError: nodemailer.createTransporter is not a function\n' +
    '    at EmailService.initializeTransporter (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:81:37)\n' +
    '    at new EmailService (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:10:10)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:486:34)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1208:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1024:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1233:19)\n' +
    '    at require (node:internal/modules/helpers:179:18)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:12:31)',
  timestamp: '2025-06-16 05:15:54'
}
{
  service: 'uny-lost-backend',
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  original: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
  parameters: {},
  level: 'error',
  message: "❌ Database connection failed: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
  stack: 'Error\n' +
    '    at Query.run (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.createTable (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:98:12)\n' +
    '    at async LostItem.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\model.js:942:7)\n' +
    '    at async Sequelize.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async setupDatabase (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\config\\database.js:82:7)\n' +
    '    at async startServer (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:119:5)',
  timestamp: '2025-06-16 05:15:59'
}
{
  service: 'uny-lost-backend',
  level: 'error',
  message: '❌ Email service initialization failed: nodemailer.createTransporter is not a function',
  stack: 'TypeError: nodemailer.createTransporter is not a function\n' +
    '    at EmailService.initializeTransporter (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:81:37)\n' +
    '    at new EmailService (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:10:10)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:486:34)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1208:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1024:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1233:19)\n' +
    '    at require (node:internal/modules/helpers:179:18)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:12:31)',
  timestamp: '2025-06-16 05:16:05'
}
{
  service: 'uny-lost-backend',
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  original: Error: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
    sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
    parameters: undefined
  },
  sql: "CREATE TABLE IF NOT EXISTS `lost_items` (`id` CHAR(36) BINARY , `itemName` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Dompet/Tas', 'Elektronik', 'Kendaraan', 'Aksesoris', 'Dokumen', 'Alat Tulis', 'Pakaian', 'Lainnya') NOT NULL, `lastSeenLocation` VARCHAR(255) NOT NULL, `dateLost` DATE NOT NULL, `reward` DECIMAL(10,2) DEFAULT 0, `images` JSON, `status` ENUM('active', 'has_matches', 'resolved', 'expired') DEFAULT 'active', `aiProcessed` TINYINT(1) DEFAULT false, `lastMatchedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` CHAR(36) BINARY, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;",
  parameters: {},
  level: 'error',
  message: "❌ Database connection failed: Referencing column 'userId' and referenced column 'id' in foreign key constraint 'lost_items_ibfk_1' are incompatible.",
  stack: 'Error\n' +
    '    at Query.run (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.createTable (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:98:12)\n' +
    '    at async LostItem.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\model.js:942:7)\n' +
    '    at async Sequelize.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async setupDatabase (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\config\\database.js:82:7)\n' +
    '    at async startServer (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:119:5)',
  timestamp: '2025-06-16 05:16:07'
}
{
  service: 'uny-lost-backend',
  level: 'error',
  message: '❌ Email service initialization failed: nodemailer.createTransporter is not a function',
  stack: 'TypeError: nodemailer.createTransporter is not a function\n' +
    '    at EmailService.initializeTransporter (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:81:37)\n' +
    '    at new EmailService (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:10:10)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\services\\emailService.js:486:34)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1208:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1024:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1233:19)\n' +
    '    at require (node:internal/modules/helpers:179:18)\n' +
    '    at Object.<anonymous> (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:12:31)',
  timestamp: '2025-06-16 05:19:59'
}
{
  service: 'uny-lost-backend',
  name: 'SequelizeDatabaseError',
  parent: Error: Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'lost_items_ibfk_1' SET NULL
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_COLUMN_NOT_NULL',
    errno: 1830,
    sqlState: 'HY000',
    sqlMessage: "Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'lost_items_ibfk_1' SET NULL",
    sql: 'ALTER TABLE `lost_items` ADD FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'lost_items_ibfk_1' SET NULL
      at Packet.asError (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\Lets Code\Mobile App\UNYLost\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_FK_COLUMN_NOT_NULL',
    errno: 1830,
    sqlState: 'HY000',
    sqlMessage: "Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'lost_items_ibfk_1' SET NULL",
    sql: 'ALTER TABLE `lost_items` ADD FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `lost_items` ADD FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;',
  parameters: {},
  level: 'error',
  message: "❌ Database connection failed: Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'lost_items_ibfk_1' SET NULL",
  stack: 'Error\n' +
    '    at Query.run (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async LostItem.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async setupDatabase (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\config\\database.js:82:7)\n' +
    '    at async startServer (D:\\Lets Code\\Mobile App\\UNYLost\\backend\\src\\app.js:119:5)',
  timestamp: '2025-06-16 05:20:04'
}
